version: '3.1'

services:
  roles-api:
    image: maven:3-jdk-11-slim
    container_name: roles_api_dev
    tty: true
    stdin_open: true
    command: bash
    working_dir: /app
    volumes:
      - ./src/:/app/src/
      - ./pom.xml/:/app/pom.xml
      - ./spotless.xml/:/app/spotless.xml
      - mvn_cache:/root/.m2
    ports:
      - '8080:8080'

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar

  sonarqube-db:
    image: postgres:latest
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

volumes:
  mvn_cache: